### ISSUE TITLE
app crash

### ISSUE THREAD

**Issue by fftmp** [alaskalinuxuser/app_justnotes#15]
step to reproduce:
create new note ("plus" button) -> write something -> rotate device (from album to portrait orientation or in the opposite direction) -> press save button -> crash.

This happens on AOSP Extended (always) and LineageOS (AFAIR, not always).

**Comment by alaskalinuxuser** [comment]
Good call. I've seen this happen on some ROMs as well. I'll have to do a little bit of research when I have time. As far as I know, currently the only way for me to fix it is to force a portrait or landscape mode, which makes it less user friendly for those who use it in a different orientation. But I'll look into it. Thanks!

**Comment by alaskalinuxuser** [comment]
Fixed by forcing portrait mode for now. Commit: https://github.com/alaskalinuxuser/app_justnotes/commit/70381cf800210eee36a01df4c5a96dd9ffb8dd15
