### ISSUE TITLE
Can't scroll till the bottom (keyboard) 

### ISSUE THREAD

**Issue by Klimmbimmel** [alaskalinuxuser/app_justnotes#16]
When the keyboard app is opened (starting to type/selecting the input field), it is not recognized. The scrolling range isn't adapted to the smaller field of view. I can't see the end of the text.

**Comment by alaskalinuxuser** [comment]
Good catch! I will look into this.

**Comment by alaskalinuxuser** [comment]
Added scrolling feature. Fixed with commit: https://github.com/alaskalinuxuser/app_justnotes/commit/70381cf800210eee36a01df4c5a96dd9ffb8dd15
