### ISSUE TITLE
Titles, colours, ordering and preview size

### ISSUE THREAD

**Issue by logos88** [alaskalinuxuser/app_justnotes#2]
Hi! I find your app quite useful as a notes taking app. I write some options I think it could improve it:
1. Option to put a **title** in the note. Maybe a white line when you are editing in the upper part where you can write a title or just leave it blank to stay like now.
2. Option to **change the colour** of each note easily. This makes easier to difference between them.
3. Option to **change the position or order** of a note to been able to put it the first one, the second or the last one as you please. Maybe the easiest way could be to push and drag and drop.
4. Option to **define how much of the note is previewed** in the general dashboard. Otherwise, a note with 1.000 lines for instances wouldn't let see anything, so being able to specify the number of lines in the preview would be nice.

This image is an example of how Swifnotes manage some of this issues:

![swifnotes](https://cloud.githubusercontent.com/assets/4170088/24713144/0b202398-1a25-11e7-8c1a-3b6bbd118de8.png)

**Comment by alaskalinuxuser** [comment]
Logos, thanks for the input! I will have to check on these things and decide if that is a route I want to go with this app. Thanks for the comments! By the way, did you get the app on the play store or fdroid?

**Comment by logos88** [comment]
Thanks for take them in consideration. In f-droid! :D

**Comment by alaskalinuxuser** [comment]
There were a lot of good suggestions logos88! I didn't decide to use them all, but I did add a few things with this commit: e4621d81c66be989435367742b920c191c4b18f9

I added a settings page so you can change the colors of text, title bars, and floating buttons. I also added an option to set the title length of your notes.
