### ISSUE TITLE
Default note is combing back

### ISSUE THREAD

**Issue by oktomus** [alaskalinuxuser/app_justnotes#3]
When I delete the default note, it comes back in the future. This is not as soon as I reopen the app, If I figure out when it happens, I'll tell you

**Comment by alaskalinuxuser** [comment]
I've seen this on rare occasions as well. In the code, the "default" message is created if you have no messages. I have an idea for a boolean instead, that of "first run" and if it is true, then it will create the note, but if it is false, then it will not. I will play with that and see how that works instead.

Thanks for chiming in! By the way, did you get the app on fdroid or the play store?

**Comment by oktomus** [comment]
Ok nice ! On fdroid :)

**Comment by alaskalinuxuser** [comment]
I have solved this problem by removing it altogether and implementing a help menu option instead with commit 00cf7450512281f21e22f735ec530b22b8307090. It will likely take a week to get onto f-droid. Next week I will also update on the play store.

**Comment by oktomus** [comment]
Nice, thanks for the app ! Say a word if you need help on the dev :)
