### ISSUE TITLE
export to .txt

### ISSUE THREAD

**Issue by davidhedlund** [alaskalinuxuser/app_justnotes#5]
Currently the files are exported to .justnotes even if they are just plain txt (correct)?

Please change the export extension to .txt.

**Comment by alaskalinuxuser** [comment]
Fixed with commit:
https://github.com/alaskalinuxuser/app_justnotes/commit/1a6ae5a1647fb49f13c691f9aee0c9de5dea1a28

**Comment by davidhedlund** [comment]
@alaskalinuxuser Thanks buddy.
