### ISSUE TITLE
Flawed settings activity

### ISSUE THREAD

**Issue by trikaphundo** [alaskalinuxuser/app_justnotes#7]
Opening the "settings" activity via the menu item brings up an activity which does not show all its content properly if the screen is not large enough:

![notes-landscape](https://cloud.githubusercontent.com/assets/24832650/26015057/91bd2bb0-375f-11e7-906e-bcfc4ec261fa.png)
[landscape]

![notes-portrait](https://cloud.githubusercontent.com/assets/24832650/26015063/991047b2-375f-11e7-8bb2-ea6ead16adaa.png)
[portrait]

I suggest taking advantage of the android facility to create preference activities:
[settings on Android API Guide](https://developer.android.com/guide/topics/ui/settings.html)
Or, at least, avoid using absolute values  for specifying the dimensions in the settings activity

**Comment by alaskalinuxuser** [comment]
Thanks, fixed by adding your commit in issue #8.
